export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Header from './components/header';
import Footer from './components/footer';
import './styles/global.css';
import 'tailwindcss/tailwind.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  )
}
